# Generated by Django 5.1 on 2024-08-17 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
